export const ViewEnum = {
  SIGN_UP: "SIGN_UP",
  INITIAL: "INITIAL",
  BALANCE: "BALANCE",
  EARN_POINTS: "EARN_POINTS",
  REDEEM_POINTS_OPTIONS: "REDEEM_POINTS_OPTIONS",
  REDEEM_POINTS: "REDEEM_POINTS",
};
